### ISSUE TITLE
no-unnecessary-condition error  with valid condition

### ISSUE THREAD

**Issue by andro-bosnjak** [RimacTechnology/eslint-config-rimac#25]
### Issues

- [X] I have checked [existing issues](https://github.com/RimacTechnology/eslint-config-rimac/issues) and there are no issues with the same problem.

### `eslint-config-rimac` Version You Are Using

26.0.1

### Your Config

```json
{
    "extends": [
        "@rimac-technology/eslint-config/core",
        "@rimac-technology/eslint-config/react"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "project": "./tsconfig.json"
    },
    "ignorePatterns": [
        "**/node_modules",
        "**/*.generated.ts",
        "**/*.json",
        "**/*.gql"
    ],
    "overrides": [
        {
            "files": [
                "**/cypress/**/*.{cy,cy.helper}.ts"
            ],
            "plugins": [
                "cypress"
            ],
            "rules": {
                "cypress/assertion-before-screenshot": "error",
                "cypress/no-assigning-return-values": "error",
                "cypress/no-async-tests": "error",
                "cypress/no-unnecessary-waiting": "error",
                "cypress/no-pause": "error",
                "promise/catch-or-return": "off",
                "promise/no-nesting": "off"
            }
        }
    ],
    "rules": {
        "etc/no-deprecated": [
            "error",
            {
                "ignored": {
                    "preProcessSnapshot": "name",
                    "postProcessSnapshot": "name",
                    "returnValue": "name"
                }
            }
        ]
    }
}
```

### Steps to reproduce

- Add `"noUncheckedIndexedAccess": true` to your `tsconfig.json` file
- Get value by indexing an array or object
- Check for null or undefined with  nullish coalescing operator `??`

### Expected behavior

No eslint errors

### Actual behavior

Got no-unnecessary-condition error

<img width="1080" alt="MicrosoftTeams-image (3)" src="https://user-images.githubusercontent.com/88096430/178701219-3c71d98e-4328-4c79-ac26-aaaccc7b354b.png">

but value can be undefined

<img width="1080" alt="MicrosoftTeams-image (4)" src="https://user-images.githubusercontent.com/88096430/178701809-648f81eb-dd79-4cef-a8ab-83deafc058e0.png">

### Requirements

- [X] I have read and followed the instructions above and understand that my issue will be closed if I did not provide the required information.

**Comment by vuki656** [comment]
@andro-bosnjak can you check if this still occurs?

I just tried to reproduce it on latest dashboard alpha and couldn't with the following after adding `noUncheckedIndexedAccess`: 

```ts
const list = ['1jla', '22']

const a = list[0] ?? 'hello'

// eslint-disable-next-line no-console
console.log('a: ', a)
```
