### ISSUE TITLE
Switch cases are wrongly indented

### ISSUE THREAD

**Issue by Spolja** [RimacTechnology/eslint-config-rimac#42]
<img width="197" alt="image" src="https://user-images.githubusercontent.com/12957080/198708229-adbf9440-68a4-4a5a-baeb-0439224d12ef.png">

Code above is not idented properly and no eslint errors are being reported.

**Comment by vuki656** [comment]
It's a problem with typescript eslint. Unfortunately, nothing can be really done about that until someone fixes it. 

https://github.com/typescript-eslint/typescript-eslint/issues/1824
